version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./input:/app/input
      - ./output:/app/output
    command: chorus-detection-web
    restart: unless-stopped 